services:
  fastapi:
    build: 
      context:  ../
      dockerfile: ./.docker/fastapi/Dockerfile
    ports:
      - 8080:8000
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ../fastapi:/app:cached
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8
    ports:
      - "5845:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${POSTGRES_USER}@test.com"
      PGADMIN_DEFAULT_PASSWORD : $POSTGRES_PASSWORD

